adminapp/urls.py
import adminapp.views as admin_views
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', admin_views.user_create, name='user_create'),
    path('users/', admin_views.UserListView.as_view(), name='user_list'),
    path('users/update/<int:pk>/', admin_views.user_update, name='user_update'),
    path('users/delete/<int:pk>/', admin_views.user_delete, name='user_delete'),

    path('categories/create/', admin_views.category_create, name='category_create'),
    path('categories/', admin_views.CategoryListView.as_view(), name='category_list'),
    path('categories/update/<int:pk>/', admin_views.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', admin_views.category_delete, name='category_delete'),

    path('products/create/<int:pk>/', admin_views.ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/', admin_views.ProductListView.as_view(), name='product_list'),
    path('products/update/<int:pk>/', admin_views.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', admin_views.ProductDeleteView.as_view(), name='product_delete'),
    path('products/detail/<int:pk>/', admin_views.ProductDetailView.as_view(), name='product_detail')
]

authapp/urls.py
from django.urls import path

from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<key>/', authapp.verify, name='verify')
]

basketapp/urls.py
from django.urls import path

from basketapp import views as basket

app_name = 'basketapp'

urlpatterns = [
    path('', basket.basket, name='basket'),
    path('add/<int:pk>/', basket.add, name='add'),
    path('remove/<int:pk>/', basket.remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket.edit, name='edit')
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main, name='index'),
    path('contact/', mainapp.contact, name='contact'),
    path('adminapp/', include('adminapp.urls', namespace='adminapp')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('products/', include('mainapp.urls', namespace='products')),
    path('basket/', include('basketapp.urls', namespace='basket'))
    # path('control/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

from mainapp import views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='products'),
    path('cat/<int:pk>/', mainapp.products, name='category'),
    path('cat/<int:pk>/<int:page>/', mainapp.products, name='category_page'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='название', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('-id',)


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name='категория')
    name = models.CharField(max_length=128, verbose_name='наименование')
    image = models.ImageField(upload_to='products', blank=True, verbose_name='картинка')
    short_desc = models.CharField(max_length=255, verbose_name='краткое описание')
    description = models.TextField(verbose_name='описание')
    price = models.DecimalField(decimal_places=2, max_digits=10, default=0, verbose_name='цена')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='количество')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name} ({self.category.name})'

    def delete(self):
        if self.is_active:
            self.is_active = False
        else:
            self.is_active = True
        self.save()

mainapp/views.py
import random

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404

from basketapp.models import Basket
from mainapp.models import Product
from mainapp.models import ProductCategory


def get_hot_product():
    return random.sample(list(Product.objects.all()), 1)[0]


def get_same_products(hot_product):
    products_list = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return products_list


def main(request):
    context = {
        'title': 'Главная',
        'products': Product.objects.all()[:4],
    }
    return render(request, 'mainapp/index.html', context)


def products(request, pk=None, page=1):
    links_menu = ProductCategory.objects.all()
    title = 'продукты'

    if pk is not None:
        if pk == 0:
            products_list = Product.objects.all()
            category_item = {'name': 'все', 'pk': 0}

        else:
            category_item = get_object_or_404(ProductCategory, pk=pk)
            products_list = Product.objects.filter(category__pk=pk)

        # page = request.GET('p', 1)
        paginator = Paginator(products_list, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        context = {
            'links_menu': links_menu,
            'title': 'Продукты',
            'category': category_item,
            'products': products_paginator,
        }

        return render(request, 'mainapp/products_list.html', context=context)

    hot_product = get_hot_product()

    same_products = get_same_products(hot_product)

    context = {
        'title': title,
        'links_menu': links_menu,
        'same_products': same_products,
        'hot_product': hot_product,
    }

    return render(request, 'mainapp/products.html', context=context)


def contact(request):
    context = {
        'title': 'Контакты',
    }
    return render(request, 'mainapp/contact.html', context)


def product(request, pk):
    links_menu = ProductCategory.objects.all()
    context = {
        'product': get_object_or_404(Product, pk=pk),
        'links_menu': links_menu,
        'title': 'Продукты'
    }

    return render(request, 'mainapp/product.html', context=context)

mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
  <li>
    <a href="{% url 'products:category' 0 %}"
       class="{% if request.resolver_match.kwargs.pk == '0' %}
                active
              {% endif %}"> все
    </a>
  </li>
  {% for link in links_menu %}
    <li>
      <a href="{% url 'products:category' link.pk %}"
         class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}
                  active
                {% endif %}">
        {{ link.name }}
      </a>
    </li>
  {% endfor %}
</ul>

mainapp/templates/mainapp/includes/inc_main_menu.html
<a href="{% url 'index' %}" class="logo"></a>
<ul class="menu">
    <li><a href="{% url 'index' %}" {% if request.resolver_match.url_name == 'index' %}
           class="active" {% endif %}>домой</a>
    </li>
    <li><a href="{% url 'products:products' %}" class="{% if request.resolver_match.namespace == 'products' %}
              active
            {% endif %}">
        продукты
    </a></li>
    <li><a href="{% url 'contact' %}" {% if request.resolver_match.url_name == 'contact' %} class="active" {% endif %}>контакты</a>
    </li>

    {% if user.is_superuser %}
        <li><a href="{% url 'adminapp:user_list' %}">Админка</a></li>
    {% endif %}

    {% if user.is_authenticated %}
        <li>
            <a href="{% url 'auth:edit' %}">{{ user.first_name|default:'Пользователь' }}</a>
            <a href="{% url 'auth:logout' %}">Выйти</a>
        </li>
    {% else %}
        <li>
            <a href="{% url 'auth:register' %}">Регистрация</a>
            <a href="{% url 'auth:login' %}">Войти</a>
        </li>
    {% endif %}

</ul>

<a href="#" class="search"></a>
<a href="{% url 'basket:basket' %}" class="basket">
    {% if basket %}
        {{ basket.0.total_cost|floatformat:0 }} руб.<br>
        {{ basket.0.total_quantity }} шт.
    {% endif %}
</a>